### PR TITLE
created the xml layout for the bookings page clubhouse task url: https://app.clubhouse.io/startng/story/49561/booking-page-xml

### PR DESCRIPTION
**Pull request by Bilijin**
clubhouse task url: https://app.clubhouse.io/startng/story/49561/booking-page-xml

### CODE REVIEW

**Comment by Bilijin** [comment]
Screenshot_20200619_094958_com michael afrivac

**Comment by Michaelzy27** [comment]
It has grade conflicts. And this is not the approved design. Please reach out to the designers

**Comment by Bilijin** [comment]
I just found the new designs but i can't find any design for the booking page there

**Comment by Michaelzy27** [comment]
It has grade conflicts. And this is not the approved design. Please reach out to the designers

**Pull request closed without merging**
