### PR TITLE
chore:french translations

### PR DESCRIPTION
**Pull request by Bilijin**

### CODE REVIEW

**Comment by Bilijin** [comment]
https://app.clubhouse.io/startng/story/53747/translation-feature
Screenshot_20200622_102444_com michael afrivac

**Comment by Bilijin** [comment]
Screenshot_20200622_113728_com michael afrivac

**Comment by allenbangai** [comment]
your french is bad but good work...

**Comment by Bilijin** [comment]
> your french is bad but good work...

can you help with the French?

**Comment by allenbangai** [comment]
how do i chancge lannguages...

**Comment by Bilijin** [comment]
> how do i chancge lannguages...

just change the language on your phone

**Pull request merged**
